image: python:3.8

stages:
  - test

before_script:
  - pip install -r requirements.txt
  - pip install pylint coverage
  - pip install pytest

test:
  stage: test
  script:
    - pylint *.py
    - coverage run test.py
    - coverage report